# Generated by Django 3.1.4 on 2020-12-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTime',
            new_name='OrderItem',
        ),
    ]
